'use client';
import {useEffect,useRef,useState} from 'react';
import {FLOW_LIBRARY_KEY,parseFlowLibrary,serializeFlowLibrary,type SavedFlow} from '../../lib/flow-library';
export function FlowLibrary({current,result,project,onPreview}:{current:string;result:string;project:string;onPreview:(source:string)=>void}){
 const [flows,setFlows]=useState<SavedFlow[]>([]),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[ready,setReady]=useState(false);
 const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(FLOW_LIBRARY_KEY);setFlows(raw?parseFlowLibrary(raw):[]);setReady(true);}catch{setMessage('流程庫無法讀取，原始資料保留。請先下載備份，修正後重新匯入。');}},[]);
 function save(next:SavedFlow[]){try{const raw=serializeFlowLibrary(next);localStorage.setItem(FLOW_LIBRARY_KEY,raw);setFlows(next);setReady(true);setMessage('流程庫已儲存在本機');return true;}catch(e){setMessage(`未儲存：${(e as Error).message}`);return false;}}
 function add(source:string){if(!title.trim()){setMessage('請先輸入流程名稱');return;}try{const next={id:crypto.randomUUID(),title:title.trim(),project,source,createdAt:new Date().toISOString()};if(save([...flows,next]))setTitle('');}catch(e){setMessage((e as Error).message);}}
 function download(){try{const raw=localStorage.getItem(FLOW_LIBRARY_KEY)||serializeFlowLibrary(flows);const url=URL.createObjectURL(new Blob([raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='model-graph-flows.json';a.click();URL.revokeObjectURL(url);}catch(e){setMessage((e as Error).message);}}
 return <details className="flow-library"><summary>流程庫 · {flows.length} 份</summary><p>保留同一類型的多份流程快照。編輯畫布後可另存一份，原快照不會被覆寫。</p><label>流程名稱<input aria-label="流程名稱" maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="例如 登入成功 / 權限不足"/></label><div className="ai-actions"><button disabled={!ready} onClick={()=>add(current)}>保存目前畫布</button>{result&&<button disabled={!ready} onClick={()=>add(result)}>保存本次產圖</button>}</div><div className="ai-actions"><button onClick={download}>下載流程庫備份</button><button onClick={()=>file.current?.click()}>匯入流程庫</button></div><p role="status">{message}</p>{flows.map(flow=><article className="story-card" key={flow.id}><strong>{flow.title}</strong><p>{flow.project||'未指定專案'} · {new Date(flow.createdAt).toLocaleDateString()}</p><div className="ai-actions"><button onClick={()=>onPreview(flow.source)}>預覽與載入</button><button onClick={()=>{if(window.confirm(`刪除流程快照「${flow.title}」？`))save(flows.filter(f=>f.id!==flow.id));}}>刪除</button></div></article>)}
 <input ref={file} hidden type="file" accept=".json,application/json" onChange={async e=>{const input=e.currentTarget,f=input.files?.[0];if(!f)return;try{if(f.size>2000000)throw new Error('流程庫上限 2 MB');const next=parseFlowLibrary(await f.text());if((!ready||flows.length)&&!window.confirm('匯入會取代現有流程庫。請確認已下載備份。'))return;save(next);}catch(err){setMessage((err as Error).message);}finally{input.value='';}}}/>
 </details>;
}
