'use client';
import {useState} from 'react';
import type {ProjectReport,ProjectStory} from '../../lib/desktop-ai';
import {diagramTypes} from '../../lib/diagram-types';
const labels:Record<string,string>={interrupted:'上次分析已中斷',running:'分析中',reading:'追查來源',synthesizing:'整理情境',pending:'等候分析',generating:'產圖中',ready:'可預覽',complete:'完成',partial:'部分完成',failed:'未完成',cancelled:'已取消'};
function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function ProjectReportView({report,onPreview,onRefine,disabled}:{report:ProjectReport;onPreview:(source:string)=>void;onRefine:(story:ProjectStory)=>void;disabled?:boolean}){
 const [filter,setFilter]=useState('');const all=report.themes.flatMap(t=>t.stories);const ready=all.filter(s=>s.flowStatus==='ready').length;
 return <section className="project-report" aria-label="主題式 Repo 分析結果"><header><span className="eyebrow">REPOSITORY ATLAS</span><h2>{report.title}</h2><p>{report.summary}</p><div className="report-counts"><strong>{report.themes.length} 主題</strong><strong>{all.length} Stories</strong><strong>{ready} 份 Flow</strong><span>{labels[report.status]||report.status}</span></div></header><p>{report.project} · 已讀 {report.coverage.read.length}/{report.coverage.indexed} 份可讀檔案。來源位置已核對，業務語意仍需確認。</p>{report.error&&<p role="alert" className="puml-error">{report.error}</p>}<div className="ai-actions"><button onClick={()=>download('model-graph-project-report.json',JSON.stringify(report,null,2),'application/json')}>下載完整報告與 PUML</button></div><label>篩選主題<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="例如 身分驗證、訂單或部署"/></label>
 {report.themes.filter(t=>(t.title+t.question).toLowerCase().includes(filter.toLowerCase())).map(theme=><section className="theme-section" key={theme.id}><header><span className="small-label">{labels[theme.status]||theme.status}</span><h3>{theme.title}</h3><p>{theme.question}</p><p>{theme.rationale}</p></header>{theme.error&&<p className="puml-error">{theme.error}</p>}{theme.gaps.length>0&&<details><summary>分析缺口 · {theme.gaps.length}</summary>{theme.gaps.map((gap,i)=><p key={i}>{gap}</p>)}</details>}{theme.stories.map(story=><article className="story-card" key={story.id}><span className="small-label">{diagramTypes[story.diagram].name} · {labels[story.flowStatus]||story.flowStatus}</span><h4>{story.title}</h4><p>{story.summary}</p><p><strong>觸發：</strong>{story.trigger}</p><div className="ai-actions">{story.source&&<><button className="primary" onClick={()=>onPreview(story.source!)}>預覽／載入 Flow</button><button onClick={()=>download(`${story.id}.puml`,story.source!,'text/plain')}>下載 PUML</button></>}<button disabled={disabled} onClick={()=>onRefine(story)}>帶回 Prompt 修改</button>{story.draftSource&&<button onClick={()=>onPreview(story.draftSource!)}>修正未通過的草稿</button>}</div>{story.error&&<p className="puml-error">{story.error}</p>}<details><summary>{story.steps.length} 個步驟與來源依據</summary><ol>{story.steps.map((step,i)=><li key={i}><strong>{step.title}</strong><p>{step.description}</p>{step.evidence.map((e,j)=><details key={j}><summary>{e.path}:{e.startLine}–{e.endLine}</summary><pre>{e.excerpt}</pre></details>)}</li>)}</ol></details><p>待確認：{story.uncertainty}</p>{story.warnings?.map((w,i)=><p key={i}>圖表提醒：{w.message}</p>)}</article>)}</section>)}
 <details><summary>來源覆蓋與內容指紋</summary><p>指紋對應分析時讀取的內容；未宣稱覆蓋所有 runtime 行為。</p>{report.coverage.read.map(f=><p key={f.path}>{f.path}<code>{f.sha256.slice(0,16)}</code></p>)}{report.coverage.omitted.map(f=><p key={f.path}>略過 {f.path}：{f.reason}</p>)}</details><p>已完成圖表會隨分析進度保存在本機，下次啟動可恢復上次報告。畫布編輯可另存至流程庫。</p>
 </section>;
}
