'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUp, ArrowUpRight, Box, Braces, Check, ChevronDown, CircleHelp, Database, Download, Hand, Layers, Link2, Maximize, MessageSquare, Minus, MousePointer2, Plus, Redo2, Sparkles, Trash2, Undo2, Upload, User, GitBranch, Circle, CircleStop, Diamond, Workflow, Radio, Send, Server } from 'lucide-react';
import { applyPrompt, Graph, GraphNode, initialGraph, NodeKind, parseGraph, uid, edgeGeometry, sequenceHeaderY } from '../lib/graph';
import { loadWorkspace, backupRecovery, STORAGE_KEY, type WorkspaceLoad } from '../lib/workspace';
import { FlowNavigator } from './components/flow-navigator';
import { ProjectReportView } from './components/project-report';
import type { ProjectReport, RepoStory } from '../lib/desktop-ai';
import { AIPanel } from './components/ai-panel';
import { PumlEditor } from './components/puml-editor';
import { exportPuml, importPuml, type PumlResult } from '../lib/puml';
import { diagramTypes, diagramKeys, levels, kindNames, type DiagramType } from '../lib/diagram-types';
const icons={person:User,system:Box,container:Layers,component:Box,code:Braces,database:Database,service:Server,external:Box,step:Workflow,decision:Diamond,start:Circle,end:CircleStop,participant:User,source:Radio,process:GitBranch,sink:Send,state:Circle};
export default function Home(){
 const [workspaceView,setWorkspaceView]=useState<'canvas'|'report'>('canvas');
 const [projectReport,setProjectReport]=useState<ProjectReport|null>(null),[analysisBusy,setAnalysisBusy]=useState(false),[storyToRefine,setStoryToRefine]=useState<RepoStory|null>(null);
 const [recovery,setRecovery]=useState<WorkspaceLoad|null>(null);
 const [saveError,setSaveError]=useState('');
 const [fitRevision,setFitRevision]=useState(0);
 const [pumlSource,setPumlSource]=useState<string|null>(null);
 const [level,setLevel]=useState('Container');
 const [diagram,setDiagram]=useState<DiagramType>('architecture');
 const key=diagram==='c4'?level:diagram;
 const config=diagramTypes[diagram],isSequence=diagram==='sequence';
 const [graphs,setGraphs]=useState<Record<string,Graph>>(()=>Object.fromEntries(diagramKeys.map(l=>[l,initialGraph(l)])));
 const graph=graphs[key]; const [ready,setReady]=useState(false);
 const [selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState('properties'),[mode,setMode]=useState('select'),[source,setSource]=useState<string|null>(null);
 const [prompt,setPrompt]=useState(''),[note,setNote]=useState(''),[messages,setMessages]=useState<{text:string;user?:boolean}[]>([]),[status,setStatus]=useState('所有變更儲存在這部裝置');
 const [view,setView]=useState({x:0,y:0,z:.8}),[mobile,setMobile]=useState('canvas');
 const svg=useRef<SVGSVGElement>(null), upload=useRef<HTMLInputElement>(null);
 const history=useRef<Record<string,Graph[]>>({}),future=useRef<Record<string,Graph[]>>({});
 const [wire,setWire]=useState<{x:number;y:number}|null>(null);
 const wireDrag=useRef(false);
 const drag=useRef<{id:string;x:number;y:number;ox:number;oy:number;moved?:boolean}|null>(null);
 useEffect(()=>{if(projectReport){setWorkspaceView('report');setMobile('canvas');}},[projectReport?.id]);
 const node=graph.nodes.find(n=>n.id===selected), edge=graph.edges.find(e=>e.id===selected);
 useEffect(()=>{const loaded=loadWorkspace(localStorage);setGraphs(loaded.graphs);if(loaded.problems.length){setRecovery(loaded);setStatus('資料讀取異常，自動儲存已暫停');}setReady(true);},[]);
 useEffect(()=>{
  if(!ready||recovery)return;
  let saved=false;
  const save=()=>{if(saved)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(graphs));saved=true;setSaveError('');setStatus('所有變更已儲存在這部裝置');}catch{setSaveError('儲存失敗，目前變更尚未保存。請先匯出圖檔。');}};
  const timer=setTimeout(save,300);
  window.addEventListener('pagehide',save);window.addEventListener('beforeunload',save);
  return()=>{clearTimeout(timer);window.removeEventListener('pagehide',save);window.removeEventListener('beforeunload',save);};
 },[graphs,ready,recovery]);
 function resumeSaving(){if(!recovery)return;try{backupRecovery(localStorage,recovery);setRecovery(null);setSaveError('');}catch{setSaveError('原始資料備份失敗，仍保持暫停儲存；請下載原始資料並匯出目前圖檔。');}}
 function downloadRecovery(){if(recovery?.raw===null||!recovery)return;const url=URL.createObjectURL(new Blob([recovery.raw],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='model-graph-recovery.json';a.click();URL.revokeObjectURL(url);}
 function switchDiagram(type:DiagramType){setDiagram(type);setSelected(null);setSource(null);setWire(null);setMode('select');drag.current=null;wireDrag.current=false;}
 function reorderMessage(direction:number){const i=graph.edges.findIndex(e=>e.id===selected),j=i+direction;if(i<0||j<0||j>=graph.edges.length)return;const edges=[...graph.edges];[edges[i],edges[j]]=[edges[j],edges[i]];update({...graph,edges});}
 function snapshot(){history.current[key]=[...(history.current[key]||[]).slice(-49),structuredClone(graph)];future.current[key]=[];}
 function update(g:Graph,record=true){if(record){try{g=parseGraph(g);}catch(e){setSaveError(`變更未套用：${(e as Error).message}`);return false;}snapshot();}setGraphs(p=>({...p,[key]:g}));return true;}
 function patchNode(p:Partial<GraphNode>){update({...graph,nodes:graph.nodes.map(n=>n.id===selected?{...n,...p}:n)});}
 function undo(redo=false){const a=redo?future:history,b=redo?history:future;const previous=a.current[key]?.pop();if(previous){b.current[key]=[...(b.current[key]||[]),graph];update(previous,false);setSelected(null);}}
 function remove(){update({...graph,nodes:graph.nodes.filter(n=>n.id!==selected),edges:graph.edges.filter(e=>e.id!==selected&&e.source!==selected&&e.target!==selected),notes:graph.notes.filter(n=>n.nodeId!==selected)});setSelected(null);}
 function add(kind:NodeKind){if(graph.nodes.length>=150){setStatus('最多 150 個節點');return;}const id=uid();update({...graph,nodes:[...graph.nodes,{id,kind,name:`New ${kindNames[kind]}`,description:'點選右側屬性編輯內容',technology:'',x:isSequence?Math.max(0,...graph.nodes.map(n=>n.x))+330:100+(graph.nodes.length%3)*330,y:isSequence?sequenceHeaderY(graph):100+Math.floor(graph.nodes.length/3)*240}]});setSelected(id);setTab('properties');}
 function connect(target:string){if(source&&(source!==target||diagram==='lifecycle'||isSequence)){if(graph.edges.length>=500){setStatus('最多 500 條關係');return;}update({...graph,edges:[...graph.edges,{id:uid(),source,target,label:config.relation,...(isSequence?{messageType:'call' as const}:{})}]});setSource(null);setMode('select');}else setSource(target);}
 function fit(){if(!graph.nodes.length)return;const r=svg.current?.getBoundingClientRect();if(!r||r.width<=0||r.height<=0)return;const minX=Math.min(...graph.nodes.map(n=>n.x))-60,minY=Math.min(...graph.nodes.map(n=>n.y))-100,maxX=Math.max(...graph.nodes.map(n=>n.x))+300,maxY=isSequence?sequenceHeaderY(graph)+330+graph.edges.length*66:Math.max(...graph.nodes.map(n=>n.y))+210;const z=Math.min(1.3,r.width/(maxX-minX),r.height/(maxY-minY));setView({x:(r.width-(maxX-minX)*z)/2-minX*z,y:(r.height-(maxY-minY)*z)/2-minY*z,z});}
 useEffect(()=>{const t=setTimeout(fit,100);return()=>clearTimeout(t);},[key,mobile,ready,fitRevision,workspaceView]);
 function generate(){if(!prompt.trim())return;try{const next=applyPrompt(graph,prompt.trim(),diagram);update(next);setMessages(m=>[...m,{text:prompt,user:true},{text:`已更新畫布：${next.nodes.length} 個節點、${next.edges.length} 條關係。你可以拖拉節點，或選取後編輯。`}]);setPrompt('');setSelected(null);}catch(e){setMessages(m=>[...m,{text:prompt,user:true},{text:(e as Error).message}]);}}
 function applyPuml(result:PumlResult){const target=result.diagram==='c4'?result.level:result.diagram;history.current[target]=[...(history.current[target]||[]).slice(-49),structuredClone(graphs[target])];future.current[target]=[];setGraphs(p=>({...p,[target]:result.graph}));setLevel(result.level);switchDiagram(result.diagram);setPumlSource(null);setMobile('canvas');setStatus('PUML 已套用，可復原');setWorkspaceView('canvas');setFitRevision(v=>v+1);}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({version:2,diagram,...(diagram==='c4'?{level}:{}),graph},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`model-graph-${key.toLowerCase()}.json`;a.click();URL.revokeObjectURL(url);}
 return <main className="studio">
 <header className="topbar"><div className="brand"><span className="brandmark"><Layers size={20}/></span><h1>model<span>graph</span></h1><span className="beta">LAB</span></div><div className="project-name">Untitled diagram <ChevronDown size={14}/><span className="save-dot"/></div><div className="top-actions"><button className="puml-launch" onClick={()=>setPumlSource(exportPuml(graph,diagram,level))} aria-label="開啟 PUML 匯入匯出"><Braces size={16}/> PUML</button><button onClick={()=>upload.current?.click()} title="匯入 JSON 或 PUML" aria-label="匯入 JSON 或 PUML"><Upload size={16}/><span>匯入</span></button><button onClick={download} aria-label="匯出 JSON"><Download size={16}/><span>匯出 JSON</span></button><span className="avatar">N</span></div></header>
 <nav className="mobile-nav">{[['chat','對話'],['canvas','畫布'],['inspector','屬性 / 註解']].map(([id,label])=><button className={mobile===id?'active':''} onClick={()=>setMobile(id)} key={id}>{label}</button>)}</nav>
 {(recovery||saveError)&&<div className="recovery-banner" role="alert"><span>{recovery?`資料讀取異常（${recovery.problems.join('、')}），自動儲存已暫停，原始資料未被覆寫。`:saveError}</span>{recovery&&<><button onClick={downloadRecovery} disabled={recovery.raw===null}>下載原始資料</button><button onClick={resumeSaving} disabled={recovery.raw===null}>備份並恢復儲存</button></>}{recovery&&saveError&&<span>{saveError}</span>}</div>}
 {projectReport&&<nav className="workspace-view-tabs" aria-label="工作區檢視"><button aria-pressed={workspaceView==='report'} onClick={()=>{setWorkspaceView('report');setMobile('canvas');}}>主題報告</button><button aria-pressed={workspaceView==='canvas'} onClick={()=>{setWorkspaceView('canvas');setMobile('canvas');}}>圖表畫布</button></nav>}
 <div className={`workspace ${workspaceView==='report'?'show-report':''}`}>
 <aside className={`chat-panel ${mobile==='chat'?'mobile-show':''}`}><div className="panel-heading"><span><Sparkles size={17}/> 設計助理</span><span className="small-label">STUDIO</span></div><div className="conversation">{!projectReport&&<><div className="intro-icon"><Sparkles size={23}/></div><h2>讓想法，有個形狀。</h2><p>從一段描述開始，逐步建構你的系統。每一個節點，都能繼續編輯。</p><div className="assistant-message"><span className="eyebrow">開始你的圖表設計</span><p>{config.description}</p><div className="example-card"><span><Layers size={16}/> {config.sample}</span><small>{config.english}{diagram==='c4'?` · ${level}`:' diagram'}</small><div className="mini-diagram">□ <i>⟶</i> □ <i>⟶</i> ▤</div></div></div></>}{projectReport&&<p>主題報告已顯示在工作區，可選擇任一 Flow 預覽或繼續修改。</p>}{messages.map((m,i)=><div key={i} className={m.user?'user-message':'assistant-message'}>{m.text}</div>)}</div><div className="composer-area"><button className="suggestion" onClick={()=>setPrompt(config.prompt)}><Plus size={14}/> 試用{config.name}指令 <ArrowUpRight size={14}/></button><AIPanel onReport={setProjectReport} onBusy={setAnalysisBusy} storyToRefine={storyToRefine} prompt={prompt} current={exportPuml(graph,diagram,level)} diagram={diagram} level={level} selection={selected||''} onDiagram={(type,nextLevel)=>{setLevel(nextLevel);switchDiagram(type);}} onPrompt={setPrompt} onLocal={generate} onPreview={setPumlSource}/></div></aside>
 {workspaceView==='report'&&<section className={`report-workspace ${mobile==='canvas'?'mobile-show':''}`}>{projectReport&&<ProjectReportView key={projectReport.id} report={projectReport} onPreview={setPumlSource} onRefine={story=>{if(story.source){const parsed=importPuml(story.source);if(!parsed.errors.length)applyPuml(parsed);}setStoryToRefine({...story});setMobile('chat');}} disabled={analysisBusy}/>}</section>}
 <section className={`canvas-panel ${mobile==='canvas'?'mobile-show':''}`}><div className="canvas-header"><div><span className="eyebrow">WORKSPACE / {config.english.toUpperCase()}</span><h2>{config.name} <span>{graph.nodes.length} nodes</span></h2></div><span className="live-badge"><span className="save-dot"/> 可編輯</span></div><div className="diagram-selector"><label htmlFor="diagram-type">圖表類型</label><select id="diagram-type" value={diagram} onChange={e=>switchDiagram(e.target.value as DiagramType)}>{Object.entries(diagramTypes).map(([id,t])=><option key={id} value={id}>{t.name} · {t.english}</option>)}</select></div>{diagram==='c4'?<div className="level-bar"><span>C4 MODEL</span>{levels.map((l,i)=><button key={l} className={level===l?'active':''} onClick={()=>{setLevel(l);setSelected(null);setSource(null);setWire(null);setMode('select');}}><small>{i+1}</small>{l}</button>)}</div>:<div className="diagram-summary">{config.description}</div>}
 <FlowNavigator graph={graph} selected={selected} onSelect={id=>{setSelected(id);setTab('properties');}}/>
 <div className="canvas-wrap"><div className="canvas-caption"><span className="caption-dot"/> {diagram==='c4'?level.toUpperCase():config.english.toUpperCase()} VIEW <span>/</span> {config.sample}</div>
 <svg ref={svg} className={`graph-canvas mode-${mode}`} aria-label={`可編輯的${config.name}畫布`} onPointerDown={e=>{if(e.target===e.currentTarget){setSelected(null);if(mode==='pan'){drag.current={id:'pan',x:e.clientX,y:e.clientY,ox:view.x,oy:view.y};e.currentTarget.setPointerCapture(e.pointerId);}}}} onPointerMove={e=>{if(wireDrag.current){const r=e.currentTarget.getBoundingClientRect();setWire({x:(e.clientX-r.left-view.x)/view.z,y:(e.clientY-r.top-view.y)/view.z});return;}const d=drag.current;if(!d)return;if(d.id==='pan')setView(v=>({...v,x:d.ox+e.clientX-d.x,y:d.oy+e.clientY-d.y}));else {if(!d.moved){if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<3)return;snapshot();d.moved=true;}update({...graph,nodes:graph.nodes.map(n=>n.id===d.id?{...n,x:d.ox+(e.clientX-d.x)/view.z,y:isSequence?d.oy:d.oy+(e.clientY-d.y)/view.z}:n)},false);}}} onPointerUp={e=>{if(wireDrag.current){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-node-id]')?.getAttribute('data-node-id');if(target&&(target!==source||diagram==='lifecycle'||isSequence))connect(target);wireDrag.current=false;setWire(null);}drag.current=null;}} onPointerCancel={()=>{drag.current=null;wireDrag.current=false;setWire(null);setSource(null);}}>
 <defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#677786"/></marker></defs><g transform={`translate(${view.x},${view.y}) scale(${view.z})`}>
 {isSequence&&graph.nodes.map(n=><line key={`life-${n.id}`} className="lifeline" x1={n.x+120} x2={n.x+120} y1={sequenceHeaderY(graph)+132} y2={sequenceHeaderY(graph)+280+graph.edges.length*66}/>)}
 {graph.edges.map((e,i)=>{const a=graph.nodes.find(n=>n.id===e.source)!,b=graph.nodes.find(n=>n.id===e.target)!;const {d,x,y}=edgeGeometry(graph,e,i,isSequence);return <g key={e.id} className={`edge ${e.messageType==='return'?'return-message':''} ${selected===e.id?'selected':''}`} role="button" tabIndex={0} aria-label={`${isSequence?'訊息':'關係'} ${a.name} 到 ${b.name}`} onClick={()=>{setSelected(e.id);setTab('properties');}} onKeyDown={k=>{if(k.key==='Enter'){setSelected(e.id);setTab('properties');}}}><path className="edge-hit" d={d}/><path className="edge-line" d={d} markerEnd="url(#arrow)"/><text x={x} y={y} textAnchor="middle">{isSequence?`${i+1}. `:''}{e.label}</text></g>;})}

 {source&&wire&&graph.nodes.some(n=>n.id===source)&&<path className="wire-preview" d={`M${graph.nodes.find(n=>n.id===source)!.x+240},${(isSequence?sequenceHeaderY(graph):graph.nodes.find(n=>n.id===source)!.y)+66} L${wire.x},${wire.y}`}/>}
 {graph.nodes.map(n=>{const Icon=icons[n.kind];const count=graph.notes.filter(c=>c.nodeId===n.id&&!c.resolved).length;return <g key={n.id} data-node-id={n.id} transform={`translate(${n.x},${isSequence?sequenceHeaderY(graph):n.y})`} className={`graph-node ${n.kind} ${selected===n.id?'selected':''} ${source===n.id?'connecting':''}`} role="button" tabIndex={0} aria-label={`編輯 ${n.name}`} onKeyDown={e=>{if(e.key==='Enter'){if(mode==='connect')connect(n.id);else setSelected(n.id);}if(e.key.startsWith('Arrow')){e.preventDefault();update({...graph,nodes:graph.nodes.map(v=>v.id===n.id?{...v,x:v.x+(e.key==='ArrowRight'?10:e.key==='ArrowLeft'?-10:0),y:isSequence?v.y:v.y+(e.key==='ArrowDown'?10:e.key==='ArrowUp'?-10:0)}:v)});}}} onPointerDown={e=>{if(mode==='connect')return;e.stopPropagation();setSelected(n.id);drag.current={id:n.id,x:e.clientX,y:e.clientY,ox:n.x,oy:n.y};svg.current?.setPointerCapture(e.pointerId);}} onClick={()=>{if(mode==='connect')connect(n.id);else setSelected(n.id);}}>{!isSequence&&n.kind==='decision'?<path className="node-body" d="M120,-16 L252,66 L120,148 L-12,66 Z"/>:<rect className="node-body" width="240" height="132" rx={!isSequence&&['start','end','state'].includes(n.kind)?48:12}/>}{!isSequence&&n.kind==='decision'?<><text className="node-kind" x="120" y="44" textAnchor="middle">條件判斷</text><text className="node-title" x="120" y="76" textAnchor="middle">{n.name.length>12?n.name.slice(0,11)+'…':n.name}</text><text className="node-tech" x="120" y="98" textAnchor="middle">{(n.technology||'').slice(0,14)}</text></>:<><rect className="node-icon-bg" x="16" y="16" width="32" height="32" rx="8"/><Icon x={23} y={23} width={18} height={18}/><text className="node-kind" x="60" y="37">{kindNames[n.kind].toUpperCase()}</text><text className="node-title" x="17" y="74">{n.name.length>23?n.name.slice(0,22)+'…':n.name}</text><text className="node-tech" x="17" y="99">{(n.technology||n.description||'尚未設定').slice(0,29)}</text></>}<circle className="port" cx="240" cy="66" r="6" onPointerDown={e=>{e.stopPropagation();setMode('connect');setSource(n.id);wireDrag.current=true;setWire({x:n.x+240,y:(isSequence?sequenceHeaderY(graph):n.y)+66});svg.current?.setPointerCapture(e.pointerId);}} onClick={e=>e.stopPropagation()}/>{count>0&&<g><circle className="note-dot" cx="228" cy="8" r="12"/><text x="228" y="12" textAnchor="middle" className="note-count">{count}</text></g>}</g>;})}</g></svg>
 <div className="toolbox">{[{Icon:MousePointer2,id:'select',label:'選取'},{Icon:Hand,id:'pan',label:'移動畫布'},{Icon:Link2,id:'connect',label:'建立關係'},{Icon:MessageSquare,id:'comment',label:'註解'}].map(({Icon,id,label})=><button key={id} title={label} aria-label={label} className={mode===id?'active':''} onClick={()=>{setMode(id);setSource(null);if(id==='comment'){setTab('comments');setMobile('inspector');}}}><Icon size={19}/></button>)}<span className="divider"/><button title="復原" aria-label="復原" onClick={()=>undo()} disabled={!history.current[key]?.length}><Undo2 size={18}/></button><button title="重做" aria-label="重做" onClick={()=>undo(true)} disabled={!future.current[key]?.length}><Redo2 size={18}/></button></div>
 <div className="zoom-tools"><button aria-label="縮小" onClick={()=>setView(v=>({...v,z:Math.max(.15,v.z-.1)}))}><Minus size={16}/></button><span>{Math.round(view.z*100)}%</span><button aria-label="放大" onClick={()=>setView(v=>({...v,z:Math.min(2.5,v.z+.1)}))}><Plus size={16}/></button><button aria-label="符合畫面" onClick={fit}><Maximize size={16}/></button></div><div className="canvas-instruction">{mode==='connect'?(source?'選取目標節點以完成連線':'選取起點，再選取目標節點'):mode==='pan'?'拖動畫布來移動視角':'拖拉節點移動位置 · 拖拉右側圓點建立關係'}</div></div><footer><span role="status"><span className="save-dot"/> {status}</span><span>{graph.edges.length} {isSequence?'messages':'relations'} · {diagram==='c4'?`C4 / ${level}`:config.english}</span></footer></section>
 <aside className={`inspector ${mobile==='inspector'?'mobile-show':''}`}><div className="inspector-tabs"><button className={tab==='properties'?'active':''} onClick={()=>setTab('properties')}>屬性</button><button className={tab==='comments'?'active':''} onClick={()=>setTab('comments')}>註解 <span>{graph.notes.filter(n=>!n.resolved).length}</span></button></div><div className="inspector-body">{tab==='properties'?<><span className="eyebrow">{node?'NODE PROPERTIES':edge?'RELATIONSHIP':'BUILD YOUR SYSTEM'}</span>{node?<><h2>{node.name}</h2><label>名稱<input maxLength={2000} value={node.name} onChange={e=>patchNode({name:e.target.value})}/></label><label>元素類型<select value={node.kind} onChange={e=>patchNode({kind:e.target.value as NodeKind})}>{Array.from(new Set([...config.kinds,node.kind])).map(k=><option value={k} key={k}>{kindNames[k]}</option>)}</select></label><label>技術 / 標籤<input maxLength={4000} value={node.technology} placeholder="例如 React · TypeScript" onChange={e=>patchNode({technology:e.target.value})}/></label><label>描述<textarea maxLength={32000} value={node.description} onChange={e=>patchNode({description:e.target.value})}/></label><button className="full-button" onClick={()=>{setSource(node.id);setMode('connect');setMobile('canvas');}}><Link2 size={16}/> 建立關係</button><button className="delete-button" onClick={remove}><Trash2 size={15}/> 刪除節點</button></>:edge?<><h2>{isSequence?'編輯訊息':'編輯關係'}</h2><p>{graph.nodes.find(n=>n.id===edge.source)?.name} → {graph.nodes.find(n=>n.id===edge.target)?.name}</p><label>關係說明<input maxLength={4000} value={edge.label} onChange={e=>update({...graph,edges:graph.edges.map(v=>v.id===edge.id?{...v,label:e.target.value}:v)})}/></label>{isSequence&&<><label>訊息類型<select value={edge.messageType||'call'} onChange={e=>update({...graph,edges:graph.edges.map(v=>v.id===edge.id?{...v,messageType:e.target.value as 'call'|'return'}:v)})}><option value="call">呼叫 / 請求（實線）</option><option value="return">回傳（虛線）</option></select></label><div className="message-order"><button disabled={graph.edges[0]?.id===edge.id} onClick={()=>reorderMessage(-1)}>↑ 提前</button><button disabled={graph.edges.at(-1)?.id===edge.id} onClick={()=>reorderMessage(1)}>↓ 延後</button></div></>}
<button className="delete-button" onClick={remove}><Trash2 size={15}/> 刪除關係</button></>:<><h2>每個系統，從節點開始</h2><p>選取畫布上的元素，編輯名稱、技術與描述。</p><div className="empty-selection"><MousePointer2 size={24}/><span>尚未選取元素</span></div></>}<div className="section-divider"/><span className="eyebrow">新增元素</span><div className="node-palette">{config.kinds.map(kind=>{const label=kindNames[kind];return [kind,label] as const;}).map(([kind,label])=>{const Icon=icons[kind as NodeKind];return <button key={kind} onClick={()=>add(kind as NodeKind)}><Icon size={18}/><span>{label}</span><Plus size={14}/></button>;})}</div><div className="info-card"><CircleHelp size={17}/><p>{config.description}</p></div></>:<><span className="eyebrow">DESIGN CONVERSATION</span><h2>把討論留在圖上</h2><p>{node?`註解對象：${node.name}`:'先選取一個節點，即可新增註解。'}</p><label>新增註解<textarea maxLength={32000} value={note} onChange={e=>setNote(e.target.value)} placeholder="這裡需要再拆成獨立服務嗎？"/></label><button className="full-button primary" disabled={!node||!note.trim()||graph.notes.length>=500} onClick={()=>{if(update({...graph,notes:[...graph.notes,{id:uid(),nodeId:node!.id,text:note,resolved:false}]}))setNote('');}}><Plus size={16}/> 新增註解</button>{graph.notes.length===0&&<div className="empty-selection"><MessageSquare size={24}/><span>還沒有註解</span></div>}{graph.notes.map(n=><div className={`comment-card ${n.resolved?'resolved':''}`} key={n.id}><button className="comment-node" onClick={()=>setSelected(n.nodeId)}>{graph.nodes.find(v=>v.id===n.nodeId)?.name}</button><p>{n.text}</p><button onClick={()=>update({...graph,notes:graph.notes.map(v=>v.id===n.id?{...v,resolved:!v.resolved}:v)})}><Check size={14}/>{n.resolved?'重新開啟':'標記已解決'}</button></div>)}</>}</div><div className="inspector-footer"><Layers size={16}/> Architecture, in the making.</div></aside></div>
 <input type="file" ref={upload} hidden accept=".json,.puml,.plantuml,.pu,application/json,text/plain" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>2_000_000)throw new Error('圖檔上限 2 MB');const content=await f.text();if(/\.(puml|plantuml|pu)$/i.test(f.name)||content.trimStart().startsWith('@startuml')){setPumlSource(content);e.target.value='';return;}const data=JSON.parse(content);const g=parseGraph(data.graph);if(data.diagram&&data.diagram!==diagram)throw new Error('請先切換到此檔案的圖表類型再匯入');if(data.level&&data.level!==level&&diagram==='c4')throw new Error('請先切換到此檔案的 C4 層級再匯入');update(g);setSelected(null);setStatus('圖檔已匯入目前畫布');setFitRevision(v=>v+1);}catch(err){setStatus((err as Error).message);}e.target.value='';}}/>
 {pumlSource!==null&&<PumlEditor initialSource={pumlSource} onClose={()=>setPumlSource(null)} onApply={applyPuml}/>}
 </main>;
}
